# Generated by Django 4.1.3 on 2022-11-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
