# Generated by Django 4.1.3 on 2022-11-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_vote', '0003_voter_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='voter',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
