# Generated by Django 4.1.3 on 2022-11-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_vote', '0005_candidate_positionid_votes_candidated_voted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='positionid',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='candidate_voted',
        ),
    ]
