# Generated by Django 4.1.3 on 2022-11-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_vote', '0006_rename_positionid_candidate_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='course',
            field=models.CharField(choices=[('BIT', 'Information Technology'), ('LLB', 'LAW'), ('M', 'Medicine'), ('SWASWA', 'SOCIAL WORKS')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
