# Generated by Django 4.1.3 on 2022-12-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_vote', '0008_voter_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votes',
            new_name='Vote',
        ),
        migrations.AlterField(
            model_name='voter',
            name='course',
            field=models.CharField(choices=[('BIT', 'Information Technology'), ('LLB', 'LAW'), ('M', 'Medicine'), ('SWASWA', 'SOCIAL WORKS'), ('BCOM', 'Bachelor In Commerce')], max_length=20),
        ),
    ]
