# Generated by Django 4.1.3 on 2022-12-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_vote', '0009_rename_votes_vote_alter_voter_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
