# Generated by Django 4.0.2 on 2023-01-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_vote', '0010_alter_position_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='birth_date',
            field=models.DateField(auto_now=True),
        ),
    ]
